
server:
  appKey: ${APP_KEY:test}
  port: ${PORT:8080}


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus